server:
  port : 8001
  servlet:
    context-path: /member

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_member?characterEncoding=UTF8&autoReconnect=true&serverTimezone=America/Toronto
    username: train_member
    password: train_password
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.he.train.member.mapper: trace